---
- hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Node.js dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - software-properties-common

    - name: fix GPG key
      shell: "curl -fsSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -"

    - name: Add NodeSource repository
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_14.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes
        filename: nodesource

    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    - name: Install build-essential
      apt:
        name: build-essential
        state: present
